// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTMTvDJ61tJ1HlcskFFDpq_N0LfQx3V6s',
    appId: '1:184425431862:web:38fc47d858e3c4436c2997',
    messagingSenderId: '184425431862',
    projectId: 'hedeaty-d434d',
    authDomain: 'hedeaty-d434d.firebaseapp.com',
    storageBucket: 'hedeaty-d434d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDrOXGZzthoOg4c1Gb2exLNjS95fMRVxA',
    appId: '1:184425431862:android:686ea2ff6821cd646c2997',
    messagingSenderId: '184425431862',
    projectId: 'hedeaty-d434d',
    storageBucket: 'hedeaty-d434d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBypQlBHYWidLgwB1pGH_naegD6zS-_cAM',
    appId: '1:184425431862:ios:043dc7e8a65e39e86c2997',
    messagingSenderId: '184425431862',
    projectId: 'hedeaty-d434d',
    storageBucket: 'hedeaty-d434d.firebasestorage.app',
    iosBundleId: 'com.example20P8736.hediatyAppp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBypQlBHYWidLgwB1pGH_naegD6zS-_cAM',
    appId: '1:184425431862:ios:043dc7e8a65e39e86c2997',
    messagingSenderId: '184425431862',
    projectId: 'hedeaty-d434d',
    storageBucket: 'hedeaty-d434d.firebasestorage.app',
    iosBundleId: 'com.example20P8736.hediatyAppp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTMTvDJ61tJ1HlcskFFDpq_N0LfQx3V6s',
    appId: '1:184425431862:web:ea0a6be096c1dc876c2997',
    messagingSenderId: '184425431862',
    projectId: 'hedeaty-d434d',
    authDomain: 'hedeaty-d434d.firebaseapp.com',
    storageBucket: 'hedeaty-d434d.firebasestorage.app',
  );
}
